### ISSUE TITLE
Identity.Whoami returns nil Account struct

### ISSUE THREAD

**Issue by drlogout** [aetrion/dnsimple-go#24] opened 2016-04-21 13:17 UTC
Identity.Whoami returns nil Account struct:

```go
whoami, err := client.Identity.Whoami()
if err != nil {
	log.Fatal(err)
}
fmt.Println(whoami.Data.Account) // <nil>
```

**Comment by weppos** [comment] 2016-04-21 14:50
How are you authenticating? Are you using an Oauth token or other authentication mechanisms?

**Comment by drlogout** [comment] 2016-04-22 10:07
with Oauth token
```go
client := dnsimple.NewClient(dnsimple.NewOauthTokenCredentials(oauthToken))
```

**Comment by weppos** [comment] 2016-04-22 10:08
How did you generate the token? Is it generated as:

- Oauth token via Oauth dance
- User access token
- Account access token

**Comment by drlogout** [comment] 2016-04-22 10:09
Account access token

**Comment by weppos** [comment] 2016-04-22 10:10
This is very strange. Can you please provide the HTTP result of a curl request? Please remove specific IDs or credentials.

**Comment by weppos** [comment] 2016-04-26 14:51
@drlogout any update?

**Comment by weppos** [comment] 2016-05-26 12:05
Closing as can't reproduce. @drlogout please feel free to reopen when you can provide the requested info.

**Closed by weppos** 2016-05-26 12:05 UTC
